// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config({
  path: ".env"
});

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: process.env.NODE_ENV == "production" ? "node dist/src/infra/prisma/seed.js" : "tsx src/infra/prisma/seed.ts",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});